# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

      - uses: ./.github/actions/install
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

      - name: Check types
        run: yarn build:types
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

      - uses: ./.github/actions/install
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

      - name: Run lint
        run: yarn lint
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

      - uses: ./.github/actions/install
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

      - name: Run tests
        run: yarn test
        if:
          "!contains(github.event.head_commit.message, 'chore(release): version
          packages')"

  release:
    name: Version + Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [compile, lint, test]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/install

      - name: Setup Release Git User
        run: |
          git config --global user.email "robot@rolfs.sh"
          git config --global user.name "Robot Rolfs"

      - name: Publish packages
        uses: changesets/action@v1
        with:
          commit: |
            chore(release): version packages
          publish: yarn release
          title: 'ðŸ“¦ Version Packages'
          version: yarn packages:version
        env:
          NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [compile, lint, test]

    steps:
      - uses: actions/checkout@v3

      - name: Set branch variables
        shell: bash
        id: vars
        run: echo "base=$(git rev-parse $(git tag --list 'emulator@deploy.*' --sort=version:refname | tail -1) | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Echo
        run: echo ${{ steps.vars.outputs.base }}

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.vars.outputs.base }}
          filters: |
            emulator:
              - 'applications/emulator/**'
              - fly.emulator.toml

      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: steps.changes.outputs.emulator == 'true'

      - name: Deploy emulator
        if: steps.changes.outputs.emulator == 'true'
        run: flyctl deploy . --remote-only --config fly.emulator.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Install jq
        if: steps.changes.outputs.emulator == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Get deployed version
        if: steps.changes.outputs.emulator == 'true'
        id: version
        run: echo "value=$(flyctl -c fly.emulator.toml info --json | jq '.Version' | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Tag deploy commit
        if: steps.changes.outputs.emulator == 'true'
        shell: bash
        run: git tag "emulator@deploy.${{ steps.version.outputs.value }}"

      - name: Push tags
        if: steps.changes.outputs.emulator == 'true'
        shell: bash
        run: git push --tags
